= GHIA IV.
:toc:
:note-caption: :information_source:
:warning-caption: :warning:

== Zadání úkolu 4

Vaším úkolem za 5 bodů je vytvořit vlastní testy k balíčku `ghia` pomocí frameworku
``pytest`` a knihovny ``betamax``. Není nutné použít ``flexmock``, pokud to nepotřebujete.

Námi dodávané testy jsou tz. _akceptační_, skoro až _integrační_. Testují aplikaci
z venku, jako black box a navíc proti živému API. Rozšiřte testovací sadu o testy
_jednotkové_: tedy testy, které testují vaše vlastní metody, funkce, třídy apod.
Vaše testy již nesmí komunikovat s reálným GitHub API.

NOTE: Pokud jste předchozí úkoly nedělali a nebo neprochází testy,
můžete použít https://github.com/cvut/ghia/tree/v0.3[naše referenční řešení].

=== Podmínky:

* Musí fungovat `setup.py test` a to nejen z gitu, ale i při rozbalení archivu `sdist`.
* Všechny testovací závislosti se musí při uvedeném příkazu nainstalovat.
** Je nutné správně rozlišit testovací a runtime závislosti.
* Testy samotné musí fungovat offline a bez nutnosti mít přístupové údaje k API.
* Spuštění testů i znovu-nahrání kazet musí být zdokumentováno v `README`. Je nutné umožnit všem znovunahrát kazety (tedy i lidem, kteří nemají přístup k vašemu GitHub účtu). Pro (znovu)vytvoření situace pro nahrání kazet můžete (ale nemusíte) použít (či upravit) skript `setup.sh` z našich současných testů.
* Nahrané kazety musí být v gitu a být součástí balíčku (ale neinstalují se).
* Žádné nahrané kazety (ani jiné soubory) nesmí obsahovat citlivé údaje.
* Alespoň část testu by měla být parametrická.
* Musí být použit nativní způsob pytest testů (pytest umí spouštět i testy pro `unittest` apod.).
* Testuje se všechno ++*++.
* Testy musí běžet i na Travis CI (případně jiném veřejném CI).

+*+ Záměrně nestanovujeme podmínku na 100% pokrytí kódu testy.
Otestujte prostě kód tak, aby byly otestovány všechny podstatné součásti
včetně webové aplikace.

== Automatické testy

Námi dodané testy z minulých úloh jsou stále závazné, můžete (ale nemusíte) je
přibalit k vašim testům, ale musí být odděleny (jiná složka).

Následuje text z minula, který stále platí:

WARNING: Testy **netestují splnění tohoto úkolu**,
Testují pouze to, že se nic nerozbilo
a že funguje spuštění pomocí příkazů výše.

NOTE: Před spuštěním testů předpokládejte, že je váš balíček nainstalován.
Toho můžete docílit například pomocí `python setup.py develop`
nebo `pip install -e.`

K úkolu na moduly jsou dodány extra testy ve složce `test_module`, které simulují reálnou instalaci
vašeho balíčku `ghia` z naklonovaného repozitáře i z testovací PyPI. Navíc testují
i další náležitosti požadované v tomto zadání (sdist bez warningů, submoduly, závislosti,
klíčová slova a další metadata). Tyto testy vyžadují nastavené proměnné prostředí
`CTU_USERNAME` a `GHIA_REPO` pro získání vaší verze ghia (pipem a gitem). V rámci
testů spouští subprocesy a pokud se na vašem OS jmenují jinak nebo jsou v jiné cestě, než
standardně na Linuxu, budete muset upravit soubor `fixtures/test_config.cfg`. V případě
potřeby založte issue. Tyto testy nepracují s aktuálním kódem „kolem nich“, ale s tím, co
je dostupné přes PyPI (publikováno) a GitHub (napushováno). Testy spustíte pomocí:

[source,console]
$ python -m pytest -v test_module

K úloze existuje sada integračních/akceptačních testů (k úlohám na click+requests a flask).
Pro jejich spuštění nainstalujte do virtuálního prostředí balík `pytest`.

Testy vyžadují určitý setup repozitáře v rámci organizace MI-PYT-ghia, do
které budete pozváni po zaslání emailu s Vaším GitHub účtem některému ze
cvičících. Pro jeho vytvoření použijte skript `setup.sh` z adresáře `tests_environment`.
Je třeba nastavit proměnné prostředí `GITHUB_TOKEN` a `GITHUB_USER`.
Token musí příslušet danému uživateli a mít scope `repo`.
Skript je potřeba spouštět z adresáře `tests_environment`.

Skript využívá program https://hub.github.com/[hub],
který si *nejprve zprovozněte*. Potřebujete alepsoň verzi 2.8.3.
Skript je otestován na Linux i
Windows (pomocí https://gitforwindows.org[git bash]).

[source,console]
$ cd tests_environment
$ export GITHUB_USER=anicka
$ export GITHUB_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$ ./setup.sh

Testy jsou napsané tak, že pokud váš program funguje dle zadání,
dají se pouštět opakovaně. Pokud ale dle zadání nefunguje,
je třeba smazat repozitář a vytvořit jej s issues znova pomocí
skriptu `tests_environment/delete.sh` (potřeba scope `delete_repo`).
Vytváření repozitáře s issues může trvat jednotky minut. Pokud
bude správně fungovat strategie `change`, pak poslední test v souboru
`test_behavior.py` (se jménem `test_reset`) zajistí nastavení na
úvodní a nebude již potřeba mazat repozitář a vytvářet jej znova.

Pro spuštění testů nastavte stejné proměnné prostředí (`GITHUB_TOKEN`
a `GITHUB_USER`).

[source,console]
$ export GITHUB_USER=anicka
$ export GITHUB_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$ python -m pytest -v tests

Testy si můžete zkopírovat k sobě do repozitáře, považujte je za Public Domain.
Nepřidejte ale do repozitáře omylem soubor `auth.real.cfg`,
který se v průběhu testů dočasně vytváří a obsahuje váš token.

NOTE: Testy proti živému API, navíc napsané tak,
že se jednotlivé testy navzájem ovlivňují, jsou ukázkou toho,
jak se to nemá dělat.
Pokud narazíte v testech na problém, nebo nevíte jak dál, zeptejte se.
K tomu, jak se to dělá pořádně, se v předmětu dostaneme později.

WARNING: Testy netestují barevnost výstupu. I neobarvený výstup projde testy.
Barevnost kontrolujte očima. Implementace, která projde testy, **není** automaticky
hodnocena plným počtem bodů.

== Odevzdání úkolu

Úkol odevzdáváte tradičně s tagem `v0.4` a nahráním nové verze na testovací
PyPI. Použijte verzi 0.4 (případně 0.4.x v souladu s tagem).
