= GHIA V.
:toc:
:note-caption: :information_source:
:warning-caption: :warning:

== Zadání úkolu 5

Vaším úkolem za 5 bodů je vytvořit pomocí http://www.sphinx-doc.org[Sphinx] 
dokumentaci k vašemu projektu `ghia`.
(V ojedinělých případech je možné po e-mailové domluvě místo toho vytvořit dokumentaci k projektu `edgemaze`.)

Měla by obsahovat textovou část, ze které bude jasné, co je, k čemu je,
jak se nainstaluje a jak se používá vaše aplikace. Můžete předpokládat, že
uživatel ví, co je to GitHub, issue, pull request, label, asignee, repozitář apod.
Nepředpokládejte ale, že ví, kde najde API token či webhook, že ví, co to je,
jak se k nim chovat apod.

Pokud hypoteticky ukážeme dokumentaci kolegům, kteří nikdy neviděli zadání
vašeho úkolu, musí to pro ně být stejně pochopitelné.

Dále by dokumentace měla obsahovat textovou část s ukázkami kódu, které se
testují pomocí doctestu. Tato část může vysvětlovat, jak váš kód použít pro
výrobu jiné aplikace, nebo může popisovat, jak aplikace uvnitř funguje.

V dokumentaci by měla existovat kapitola s *kompletní* API dokumentací vašich
modulů, tříd, funkcí apod. Všechny tyto věci musí mít v kódu dokumentační
řetězce, které v dokumentaci musí být zobrazeny (t.j. změna dokumentačního
řetězce se automaticky promítne ve vygenerované dokumentaci).

Jak sestavit a testovat dokumentaci by mělo být jasné z `README.rst`
(a to musí mít http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html[reStructuredText]
syntaxi). 
`README.rst` musí obsahovat základní informace o projektu, pokročilejší věci patří do Sphinx dokumentace.

Generování dokumentace ani doctesty nesmí způsobit chybu ani varování.
Potlačení chybových a varovných hlášek (např. konfigurací, přesměrováním
*stderr*, apod.) je povoleno jen po konzultaci s cvičícím.

Dokumentace musí být v angličtině.

Dosavadní funkcionalita aplikace musí být samozřejmě zachována.

Za fungující publikaci smysluplné dokumentace na https://readthedocs.org/[Read the Docs] je možné získat bod navíc.

== Automatické testy

Námi dodané testy z minulých úloh jsou stále závazné.

Následuje text z minula, který stále platí:

WARNING: Testy **netestují splnění tohoto úkolu**,
Testují pouze to, že se nic nerozbilo
a že funguje spuštění pomocí příkazů výše.

NOTE: Před spuštěním testů předpokládejte, že je váš balíček nainstalován.
Toho můžete docílit například pomocí `python setup.py develop`
nebo `pip install -e.`

K úkolu na moduly jsou dodány extra testy ve složce `test_module`, které simulují reálnou instalaci
vašeho balíčku `ghia` z naklonovaného repozitáře i z testovací PyPI. Navíc testují
i další náležitosti požadované v tomto zadání (sdist bez warningů, submoduly, závislosti,
klíčová slova a další metadata). Tyto testy vyžadují nastavené proměnné prostředí
`CTU_USERNAME` a `GHIA_REPO` pro získání vaší verze ghia (pipem a gitem). V rámci
testů spouští subprocesy a pokud se na vašem OS jmenují jinak nebo jsou v jiné cestě, než
standardně na Linuxu, budete muset upravit soubor `fixtures/test_config.cfg`. V případě
potřeby založte issue. Tyto testy nepracují s aktuálním kódem „kolem nich“, ale s tím, co
je dostupné přes PyPI (publikováno) a GitHub (napushováno). Testy spustíte pomocí:

[source,console]
$ python -m pytest -v test_module

K úloze existuje sada integračních/akceptačních testů (k úlohám na click+requests a flask).
Pro jejich spuštění nainstalujte do virtuálního prostředí balík `pytest`.

Testy vyžadují určitý setup repozitáře v rámci organizace MI-PYT-ghia, do
které budete pozváni po zaslání emailu s Vaším GitHub účtem některému ze
cvičících. Pro jeho vytvoření použijte skript `setup.sh` z adresáře `tests_environment`.
Je třeba nastavit proměnné prostředí `GITHUB_TOKEN` a `GITHUB_USER`.
Token musí příslušet danému uživateli a mít scope `repo`.
Skript je potřeba spouštět z adresáře `tests_environment`.

Skript využívá program https://hub.github.com/[hub],
který si *nejprve zprovozněte*. Potřebujete alepsoň verzi 2.8.3.
Skript je otestován na Linux i
Windows (pomocí https://gitforwindows.org[git bash]).

[source,console]
$ cd tests_environment
$ export GITHUB_USER=anicka
$ export GITHUB_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$ ./setup.sh

Testy jsou napsané tak, že pokud váš program funguje dle zadání,
dají se pouštět opakovaně. Pokud ale dle zadání nefunguje,
je třeba smazat repozitář a vytvořit jej s issues znova pomocí
skriptu `tests_environment/delete.sh` (potřeba scope `delete_repo`).
Vytváření repozitáře s issues může trvat jednotky minut. Pokud
bude správně fungovat strategie `change`, pak poslední test v souboru
`test_behavior.py` (se jménem `test_reset`) zajistí nastavení na
úvodní a nebude již potřeba mazat repozitář a vytvářet jej znova.

Pro spuštění testů nastavte stejné proměnné prostředí (`GITHUB_TOKEN`
a `GITHUB_USER`).

[source,console]
$ export GITHUB_USER=anicka
$ export GITHUB_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$ python -m pytest -v tests

Testy si můžete zkopírovat k sobě do repozitáře, považujte je za Public Domain.
Nepřidejte ale do repozitáře omylem soubor `auth.real.cfg`,
který se v průběhu testů dočasně vytváří a obsahuje váš token.

NOTE: Testy proti živému API, navíc napsané tak,
že se jednotlivé testy navzájem ovlivňují, jsou ukázkou toho,
jak se to nemá dělat.
Pokud narazíte v testech na problém, nebo nevíte jak dál, zeptejte se.
K tomu, jak se to dělá pořádně, se v předmětu dostaneme později.

WARNING: Testy netestují barevnost výstupu. I neobarvený výstup projde testy.
Barevnost kontrolujte očima. Implementace, která projde testy, **není** automaticky
hodnocena plným počtem bodů.

== Odevzdání úkolu

Úkol odevzdáváte tradičně s tagem `v0.5` a nahráním nové verze na testovací
PyPI. Použijte verzi 0.5 (případně 0.5.x v souladu s tagem).
