== GHIA III.
:toc:
:note-caption: :information_source:
:warning-caption: :warning:

== Zadání úkolu 3

Vaším úkolem za 5 bodů je udělat z vašeho dosavadního projektu balíček
instalovatelný přes pip a nahrát jej na testovací PyPI.

Jelikož používáme všichni stejný název aplikace `ghia`,
tak pro PyPI použijte jako název `ghia_<username>`
(v reálných situacích se nedoporučuje jiný název než je jméno importovatelného modulu).

Pokud svůj kód za žádných okolností nechcete zveřejnit ani na testovací PyPI,
dejte nám vědět a domluvíme se.

NOTE: Pokud jste předchozí úkoly nedělali a nebo neprochází testy,
můžete použít https://github.com/cvut/ghia/releases/tag/v0.2[naše referenční řešení].

Podmínky (je jich hodně, ale jsou triviální):

* Váš balíček musí fungovat (viz zadání předchozích úkolů)
  po instalaci pomocí pipu do „prázdného“ virtuálního prostředí.
  Musí tedy mít správně nadefinované všechny závislosti.
* Musí obsahovat rozumný počet classsifiers a voleb pro `setup.py`.
* Podpříkazy `sdist` a `bdist_wheel` nesmí skončit chybou ani vyvolat varování.
* Musí splňovat konvence uvedené ve výukových materiálech:
** Jméno importovatelného modulu musí být `ghia` a všechny další pomocné
   moduly musí být jeho podmoduly.
** Všechny soubory `+__init__.py+` mají být víceméně prázdné a obsahovat pouze
   importy, případně nastavovat `+__all__+`.
** Verze balíčku musí odpovídat tagu. V případě iterování odevzdejte klidně verzi 0.3.x (kde x je např. 1, 2...).
* Hlavní program musí jít spouštět pomocí entrypointu `ghia` i pomocí `-m ghia`.
* Stále se musí dát z modulu `ghia` přímo importovat Flask `app` (či `create_app`).
* Pokud jste již tak neučinili, tak rozdělte aplikaci na jednotlivé
  funkční celky. Měli byste mít alespoň 3 submoduly, například:
** `cli` - vstup + výpis na konzoli z prvního úkolu,
** `web` - flask aplikace,
** `github` - klient pro komunikaci s GitHub API (společný pro `cli` a
`web`),
** případně navíc ještě oddělit logiku práce se štítky či další.
** (Pamatujte že v Pythonu není nutné každou třídu dávat do zvláštního souboru.
   Také připomínáme, že https://www.python.org/dev/peps/pep-0020/[Flat is better than nested],
   není tedy vhodné moduly do sebe nořit příliš hluboko.)
** Vyvarujte se cyklických importů!
* Zabalený modul musí obsahovat soubor s textem licence (`LICENSE`, `COPYING`) +*+
* `long_description` musí být dynamicky načten z `README`

+*+ Vhodnou licenci můžete najít na http://choosealicense.com/[choosealicense.com].
V případě, že váš kód nechcete šířit pod svobodnou licencí,
napište to do souboru vlastní podmínky. Nevymýšlejte si ale prosím vlastní
open-source licence.

== Automatické testy

Testy z minula byly mírně upraveny, aby nevolaly `python ghia.py` přímo,
ale příkaz `ghia`,
navíc byly přidány jednoduché testy, které volají `python -m ghia`.

WARNING: Testy **netestují splnění tohoto úkolu**,
Testují pouze to, že se nic nerozbilo
a že funguje spuštění pomocí příkazů výše.

NOTE: Před spuštěním testů předpokládejte, že je váš balíček nainstalován.
Toho můžete docílit například pomocí `python setup.py develop`
nebo `pip install -e.`

Nově jsou dodány extra testy ve složce `test_module`, které simulují reálnou instalaci
vašeho balíčku `ghia` z naklonovaného repozitáře i z testovací PyPI. Navíc testují
i další náležitosti požadované v tomto zadání (sdist bez warningů, submoduly, závislosti,
klíčová slova a další metadata). Tyto testy vyžadují nastavené proměnné prostředí
`CTU_USERNAME` a `GHIA_REPO` pro získání vaší verze ghia (pipem a gitem). V rámci
testů spouští subprocesy a pokud se na vašem OS jmenují jinak nebo jsou v jiné cestě, než
standardně na Linuxu, budete muset upravit soubor `fixtures/test_config.cfg`. V případě
potřeby založte issue. Tyto testy nepracují s aktuálním kódem „kolem nich“, ale s tím, co
je dostupné přes PyPI (publikováno) a GitHub (napushováno). Testy spustíte pomocí:

[source,console]
$ python -m pytest -v test_module

Následuje text z minula, který stále platí:

K úloze existuje sada testů.
Pro jejich spuštění nainstalujte do virtuálního prostředí balík `pytest`.

Testy vyžadují určitý setup repozitáře v rámci organizace MI-PYT-ghia, do
které budete pozváni po zaslání emailu s Vaším GitHub účtem některému ze
cvičících. Pro jeho vytvoření použijte skript `setup.sh` z adresáře `tests_environment`.
Je třeba nastavit proměnné prostředí `GITHUB_TOKEN` a `GITHUB_USER`.
Token musí příslušet danému uživateli a mít scope `repo`.
Skript je potřeba spouštět z adresáře `tests_environment`.

Skript využívá program https://hub.github.com/[hub],
který si *nejprve zprovozněte*. Potřebujete alepsoň verzi 2.8.3.
Skript je otestován na Linux i
Windows (pomocí https://gitforwindows.org[git bash]).

[source,console]
$ cd tests_environment
$ export GITHUB_USER=anicka
$ export GITHUB_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$ ./setup.sh

Testy jsou napsané tak, že pokud váš program funguje dle zadání,
dají se pouštět opakovaně. Pokud ale dle zadání nefunguje,
je třeba smazat repozitář a vytvořit jej s issues znova pomocí
skriptu `tests_environment/delete.sh` (potřeba scope `delete_repo`).
Vytváření repozitáře s issues může trvat jednotky minut. Pokud
bude správně fungovat strategie `change`, pak poslední test v souboru
`test_behavior.py` (se jménem `test_reset`) zajistí nastavení na
úvodní a nebude již potřeba mazat repozitář a vytvářet jej znova.

Pro spuštění testů nastavte stejné proměnné prostředí (`GITHUB_TOKEN`
a `GITHUB_USER`).

[source,console]
$ export GITHUB_USER=anicka
$ export GITHUB_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$ python -m pytest -v tests

Testy si můžete zkopírovat k sobě do repozitáře, považujte je za Public Domain.
Nepřidejte ale do repozitáře omylem soubor `auth.real.cfg`,
který se v průběhu testů dočasně vytváří a obsahuje váš token.

NOTE: Testy proti živému API, navíc napsané tak,
že se jednotlivé testy navzájem ovlivňují, jsou ukázkou toho,
jak se to nemá dělat.
Pokud narazíte v testech na problém, nebo nevíte jak dál, zeptejte se.
K tomu, jak se to dělá pořádně, se v předmětu dostaneme později.

WARNING: Testy netestují barevnost výstupu. I neobarvený výstup projde testy.
Barevnost kontrolujte očima. Implementace, která projde testy, **není** automaticky
hodnocena plným počtem bodů.

== Odevzdání úkolu

Odkazy na repozitář a balíček na testovací PyPI nám pošlete e-mailem.
Pro odevzdání v repozitáři nastavte tag `v0.3`, případně `v0.3.1`, `v0.3.2`...
